"""
Inject Section 6 comparison code into notebook.ipynb
Run: python inject_section6.py
"""
import json, uuid, os

NB_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "notebook.ipynb")

def uid():
    return uuid.uuid4().hex[:8]

def md(src):
    return {"cell_type": "markdown", "id": uid(), "metadata": {}, "source": src}

def code(src):
    return {"cell_type": "code", "execution_count": None, "id": uid(), "metadata": {}, "outputs": [], "source": src}

# ── NEW CELLS ──────────────────────────────────────────────────────────────────

CELLS = [
    # ── 6.0 Header ──
    md([
        "---\n",
        "# **SECTION 6 - Comparison and Final Results**\n",
    ]),
    md([
        "## 6.0 - Setup & Parameters\n",
        "\n",
        "We fix **hotel**, **day**, and run every algorithm on a grid of\n",
        "`budgets × start_times`.  Each run rebuilds Problem / Environment fresh.\n",
    ]),
    # ── 6.0 Code: setup ──
    code([
        "import time as _time, os, io, contextlib, math\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from matplotlib import cm\n",
        "\n",
        "# ── Grid ──\n",
        "BUDGETS     = [6, 8, 10, 12, 16, 20]\n",
        "START_TIMES = [9, 12, 14]\n",
        "VISITING_DAY = 'fri'\n",
        "\n",
        "# ── Output ──\n",
        "OUTPUT_DIR = os.path.join(os.getcwd(), 'Tests', 'Comparison_results')\n",
        "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
        "\n",
        "# ── Data ──\n",
        "landmarks   = get_landmarks()\n",
        "hotels      = get_hotels()\n",
        "time_matrix = get_time_matrix()\n",
        "selected_hotel = hotels[0]\n",
        "TOTAL_LANDMARKS = len(landmarks)\n",
        "\n",
        "ALGO_NAMES = ['Greedy', 'SA', 'GA', 'ACS', 'ABC', 'HillClimbing']\n",
        "\n",
        "print(f'Hotel       : {selected_hotel.name}')\n",
        "print(f'Landmarks   : {TOTAL_LANDMARKS}')\n",
        "print(f'Budgets     : {BUDGETS}')\n",
        "print(f'Start times : {START_TIMES}')\n",
        "print(f'Day         : {VISITING_DAY}')\n",
        "print(f'Algorithms  : {ALGO_NAMES}')\n",
        "print(f'Total runs  : {len(BUDGETS) * len(START_TIMES) * len(ALGO_NAMES)}')\n",
    ]),
    # ── 6.1 Header ──
    md([
        "## 6.1 - Comparison Run\n",
        "\n",
        "For each `(budget, start_time)` pair we initialise the three problem types\n",
        "(InformedSearch, LocalSearch, ACSEnvironment), run every algorithm,\n",
        "and collect `best_score`, `runtime`, `landmarks_visited`, `is_feasible`.\n",
    ]),
    # ── 6.1 Code: comparison loop ──
    code([
        "results = []\n",
        "counter = 0\n",
        "total   = len(BUDGETS) * len(START_TIMES) * len(ALGO_NAMES)\n",
        "\n",
        "for b in BUDGETS:\n",
        "    for s in START_TIMES:\n",
        "        # ── Build fresh problems ──\n",
        "        travel_info = {\n",
        "            'hotel': selected_hotel,\n",
        "            'Travel_day': VISITING_DAY,\n",
        "            'Travel_Time': b,\n",
        "            'type_filter': [],\n",
        "            'time_matrix': time_matrix,\n",
        "            'trip_start_time': s,\n",
        "        }\n",
        "        problem_local = TravelProblem_LocalSearch(landmarks, travel_info)\n",
        "\n",
        "        problem_informed = TravelProblem_InformedSearch(\n",
        "            hotel=selected_hotel, landmarks=landmarks, type_filter=[],\n",
        "            time_matrix=time_matrix, time_budget=b*60,\n",
        "            starting_time=s*60, visiting_day=VISITING_DAY,\n",
        "        )\n",
        "\n",
        "        env = ACSEnvironment(\n",
        "            hotel=selected_hotel, landmarks=landmarks,\n",
        "            time_matrix=time_matrix, time_budget_hours=b,\n",
        "            trip_start_time_hours=s, visiting_day=VISITING_DAY,\n",
        "        )\n",
        "\n",
        "        # ── Helper: unified scoring ──\n",
        "        def _score(lm_list):\n",
        "            if not lm_list:\n",
        "                return 0.0\n",
        "            return problem_local.evaluate(lm_list)\n",
        "\n",
        "        for algo in ALGO_NAMES:\n",
        "            counter += 1\n",
        "            row = {'algorithm': algo, 'budget': b, 'start_time': s,\n",
        "                   'best_score': 0.0, 'runtime_ms': 0.0,\n",
        "                   'landmarks_visited': 0, 'is_feasible': False, 'error': ''}\n",
        "            try:\n",
        "                # ────────── GREEDY ──────────\n",
        "                if algo == 'Greedy':\n",
        "                    t0 = _time.time()\n",
        "                    path = greedy_search(problem_informed)\n",
        "                    row['runtime_ms'] = (_time.time() - t0) * 1000\n",
        "                    if path:\n",
        "                        # path = list of state tuples; last before hotel has full visited set\n",
        "                        visited_names = set()\n",
        "                        for state in path:\n",
        "                            pos, vis, _ = state\n",
        "                            visited_names |= vis\n",
        "                        lm_list = [lm for lm in landmarks if lm.name in visited_names]\n",
        "                        row['best_score'] = _score(lm_list)\n",
        "                        row['landmarks_visited'] = len(lm_list)\n",
        "                        row['is_feasible'] = True\n",
        "\n",
        "                # ────────── SA ──────────\n",
        "                elif algo == 'SA':\n",
        "                    sa = Simulated_Annealing(problem_local,\n",
        "                             initial_temp=300, cooling_rate=0.99, max_reheats=1)\n",
        "                    t0 = _time.time()\n",
        "                    res = sa.run()\n",
        "                    row['runtime_ms'] = (_time.time() - t0) * 1000\n",
        "                    if res:\n",
        "                        row['best_score'] = _score(res)\n",
        "                        row['landmarks_visited'] = len(res)\n",
        "                        row['is_feasible'] = problem_local.valid_state(res)\n",
        "\n",
        "                # ────────── GA ──────────\n",
        "                elif algo == 'GA':\n",
        "                    ga = Genetic_Algorithm(problem_local,\n",
        "                             population_size=100, generations=80, mutation_rate=0.10)\n",
        "                    t0 = _time.time()\n",
        "                    res = ga.evolve(\n",
        "                        selection_method='tournament',\n",
        "                        crossover_method='order',\n",
        "                        mutation_method='scramble',\n",
        "                    )\n",
        "                    row['runtime_ms'] = (_time.time() - t0) * 1000\n",
        "                    if res:\n",
        "                        row['best_score'] = _score(res)\n",
        "                        row['landmarks_visited'] = len(res)\n",
        "                        row['is_feasible'] = problem_local.valid_state(res)\n",
        "\n",
        "                # ────────── ACS ──────────\n",
        "                elif algo == 'ACS':\n",
        "                    acs = AntColonySystem(env,\n",
        "                              num_ants=50, generations=100,\n",
        "                              alpha=0.5, beta=3.0, rho=0.05)\n",
        "                    t0 = _time.time()\n",
        "                    path_acs, score_acs = acs.solve()\n",
        "                    row['runtime_ms'] = (_time.time() - t0) * 1000\n",
        "                    lm_acs = [n for n in path_acs if isinstance(n, Landmark)]\n",
        "                    row['best_score'] = _score(lm_acs)\n",
        "                    row['landmarks_visited'] = len(lm_acs)\n",
        "                    row['is_feasible'] = len(lm_acs) > 0\n",
        "\n",
        "                # ────────── ABC ──────────\n",
        "                elif algo == 'ABC':\n",
        "                    with contextlib.redirect_stdout(io.StringIO()):\n",
        "                        abc = ABC_Optimization(problem_local,\n",
        "                                  colony_ratio=0.5, colony_size=60,\n",
        "                                  limit=20, iterations=100,\n",
        "                                  selection_method='rank')\n",
        "                    t0 = _time.time()\n",
        "                    state_abc, fit_abc = abc.solve()\n",
        "                    row['runtime_ms'] = (_time.time() - t0) * 1000\n",
        "                    if state_abc:\n",
        "                        row['best_score'] = _score(state_abc)\n",
        "                        row['landmarks_visited'] = len(state_abc)\n",
        "                        row['is_feasible'] = problem_local.valid_state(state_abc)\n",
        "\n",
        "                # ────────── HillClimbing ──────────\n",
        "                elif algo == 'HillClimbing':\n",
        "                    hc = hill_climbing(problem_local,\n",
        "                             num_restarts=50, base_strategy='stochastic')\n",
        "                    t0 = _time.time()\n",
        "                    cand = hc.run()\n",
        "                    row['runtime_ms'] = (_time.time() - t0) * 1000\n",
        "                    if cand and cand.state:\n",
        "                        row['best_score'] = cand.value\n",
        "                        row['landmarks_visited'] = len(cand.state)\n",
        "                        row['is_feasible'] = problem_local.valid_state(cand.state)\n",
        "\n",
        "            except Exception as e:\n",
        "                row['error'] = str(e)\n",
        "\n",
        "            results.append(row)\n",
        "            tag = '✓' if row['is_feasible'] else '✗'\n",
        "            print(f\"  [{counter:>3}/{total}]  {algo:<14} budget={b:>2}h  start={s:>2}  \"\n",
        "                  f\"-> fit={row['best_score']:>8.1f}  lm={row['landmarks_visited']:>2}  \"\n",
        "                  f\"{row['runtime_ms']:>8.1f}ms  {tag}\")\n",
        "\n",
        "df = pd.DataFrame(results)\n",
        "csv_path = os.path.join(OUTPUT_DIR, 'comparison_results.csv')\n",
        "df.to_csv(csv_path, index=False)\n",
        "print(f'\\n[OK] Results saved -> {csv_path}')\n",
        "print(f'\\nSummary (mean across all runs):')\n",
        "print(df.groupby('algorithm')[['best_score','runtime_ms','landmarks_visited']].mean()\n",
        "      .round(2).to_string())\n",
    ]),
    # ── 6.2 Header ──
    md([
        "## 6.2 - Visualization\n",
        "\n",
        "Three comparison plots:\n",
        "1. **Score vs Budget** — line chart, one subplot per start_time\n",
        "2. **Runtime vs Budget** — line chart, one subplot per start_time\n",
        "3. **Radar Chart** — multi-axis spider plot for overall comparison\n",
    ]),
    # ── Plot 1: Score vs Budget ──
    code([
        "# ═══════════════════════════════════════════════════════════════\n",
        "# Plot 1 — Score vs Budget (one subplot per start_time)\n",
        "# ═══════════════════════════════════════════════════════════════\n",
        "COLORS = {'Greedy':'#2ecc71', 'SA':'#e74c3c', 'GA':'#3498db',\n",
        "          'ACS':'#9b59b6', 'ABC':'#f39c12', 'HillClimbing':'#1abc9c'}\n",
        "MARKERS = {'Greedy':'o', 'SA':'s', 'GA':'^', 'ACS':'D', 'ABC':'P', 'HillClimbing':'X'}\n",
        "\n",
        "fig, axes = plt.subplots(1, len(START_TIMES), figsize=(6*len(START_TIMES), 5), sharey=True)\n",
        "if len(START_TIMES) == 1:\n",
        "    axes = [axes]\n",
        "\n",
        "for idx, st in enumerate(START_TIMES):\n",
        "    ax = axes[idx]\n",
        "    sub = df[df['start_time'] == st]\n",
        "    for algo in ALGO_NAMES:\n",
        "        adf = sub[sub['algorithm'] == algo].sort_values('budget')\n",
        "        ax.plot(adf['budget'], adf['best_score'],\n",
        "                color=COLORS[algo], marker=MARKERS[algo],\n",
        "                label=algo, linewidth=2, markersize=7)\n",
        "    ax.set_title(f'Start = {st}:00', fontsize=13, fontweight='bold')\n",
        "    ax.set_xlabel('Budget (hours)')\n",
        "    if idx == 0:\n",
        "        ax.set_ylabel('Fitness Score')\n",
        "    ax.grid(True, alpha=0.3)\n",
        "\n",
        "handles, labels = axes[0].get_legend_handles_labels()\n",
        "fig.legend(handles, labels, loc='lower center', ncol=len(ALGO_NAMES),\n",
        "           fontsize=10, bbox_to_anchor=(0.5, -0.05))\n",
        "fig.suptitle('Algorithm Comparison — Fitness vs Budget', fontsize=15, fontweight='bold')\n",
        "plt.tight_layout(rect=[0, 0.05, 1, 0.95])\n",
        "p1 = os.path.join(OUTPUT_DIR, 'score_vs_budget.png')\n",
        "fig.savefig(p1, dpi=150, bbox_inches='tight')\n",
        "plt.show(); plt.close(fig)\n",
        "print(f'[OK] {p1}')\n",
    ]),
    # ── Plot 2: Runtime vs Budget ──
    code([
        "# ═══════════════════════════════════════════════════════════════\n",
        "# Plot 2 — Runtime vs Budget (one subplot per start_time)\n",
        "# ═══════════════════════════════════════════════════════════════\n",
        "fig, axes = plt.subplots(1, len(START_TIMES), figsize=(6*len(START_TIMES), 5), sharey=True)\n",
        "if len(START_TIMES) == 1:\n",
        "    axes = [axes]\n",
        "\n",
        "for idx, st in enumerate(START_TIMES):\n",
        "    ax = axes[idx]\n",
        "    sub = df[df['start_time'] == st]\n",
        "    for algo in ALGO_NAMES:\n",
        "        adf = sub[sub['algorithm'] == algo].sort_values('budget')\n",
        "        ax.plot(adf['budget'], adf['runtime_ms'],\n",
        "                color=COLORS[algo], marker=MARKERS[algo],\n",
        "                label=algo, linewidth=2, markersize=7)\n",
        "    ax.set_title(f'Start = {st}:00', fontsize=13, fontweight='bold')\n",
        "    ax.set_xlabel('Budget (hours)')\n",
        "    if idx == 0:\n",
        "        ax.set_ylabel('Runtime (ms)')\n",
        "    ax.grid(True, alpha=0.3)\n",
        "    ax.set_yscale('log')  # log scale — runtimes vary by orders of magnitude\n",
        "\n",
        "handles, labels = axes[0].get_legend_handles_labels()\n",
        "fig.legend(handles, labels, loc='lower center', ncol=len(ALGO_NAMES),\n",
        "           fontsize=10, bbox_to_anchor=(0.5, -0.05))\n",
        "fig.suptitle('Algorithm Comparison — Runtime vs Budget', fontsize=15, fontweight='bold')\n",
        "plt.tight_layout(rect=[0, 0.05, 1, 0.95])\n",
        "p2 = os.path.join(OUTPUT_DIR, 'runtime_vs_budget.png')\n",
        "fig.savefig(p2, dpi=150, bbox_inches='tight')\n",
        "plt.show(); plt.close(fig)\n",
        "print(f'[OK] {p2}')\n",
    ]),
    # ── Plot 3: Radar Chart ──
    code([
        "# ═══════════════════════════════════════════════════════════════\n",
        "# Plot 3 — Radar Chart (multi-axis comparison)\n",
        "# ═══════════════════════════════════════════════════════════════\n",
        "metrics = ['Avg Score', 'Speed', 'Feasibility', 'Coverage']\n",
        "agg = df.groupby('algorithm').agg(\n",
        "    avg_score=('best_score', 'mean'),\n",
        "    avg_runtime=('runtime_ms', 'mean'),\n",
        "    feasibility=('is_feasible', 'mean'),\n",
        "    avg_lm=('landmarks_visited', 'mean'),\n",
        ").reindex(ALGO_NAMES)\n",
        "\n",
        "# Speed = inverse of runtime, normalized\n",
        "agg['speed'] = 1.0 / (agg['avg_runtime'] + 1e-9)\n",
        "agg['coverage'] = agg['avg_lm'] / TOTAL_LANDMARKS\n",
        "\n",
        "# Min-max normalize each axis to [0, 1]\n",
        "radar_cols = ['avg_score', 'speed', 'feasibility', 'coverage']\n",
        "normed = agg[radar_cols].copy()\n",
        "for c in radar_cols:\n",
        "    mn, mx = normed[c].min(), normed[c].max()\n",
        "    normed[c] = (normed[c] - mn) / (mx - mn + 1e-9)\n",
        "\n",
        "angles = np.linspace(0, 2 * np.pi, len(metrics), endpoint=False).tolist()\n",
        "angles += angles[:1]  # close the polygon\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))\n",
        "for algo in ALGO_NAMES:\n",
        "    vals = normed.loc[algo].tolist()\n",
        "    vals += vals[:1]\n",
        "    ax.plot(angles, vals, color=COLORS[algo], linewidth=2, label=algo)\n",
        "    ax.fill(angles, vals, color=COLORS[algo], alpha=0.10)\n",
        "\n",
        "ax.set_thetagrids([a * 180/np.pi for a in angles[:-1]], metrics, fontsize=12)\n",
        "ax.set_ylim(0, 1.05)\n",
        "ax.set_title('Algorithm Comparison — Radar', fontsize=15,\n",
        "             fontweight='bold', pad=25)\n",
        "ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1), fontsize=10)\n",
        "plt.tight_layout()\n",
        "p3 = os.path.join(OUTPUT_DIR, 'radar_chart.png')\n",
        "fig.savefig(p3, dpi=150, bbox_inches='tight')\n",
        "plt.show(); plt.close(fig)\n",
        "print(f'[OK] {p3}')\n",
    ]),
    # ── 6.3 Conclusions ──
    md([
        "## 6.3 - Conclusions\n",
        "\n",
        "The comparison above covers **6 algorithms** across a grid of\n",
        "`6 budgets × 3 start_times = 18 scenarios` (108 total runs).\n",
        "\n",
        "Key takeaways to fill in after running:\n",
        "- Which algorithm achieves the **highest fitness** on average?\n",
        "- Which algorithm is the **fastest**?\n",
        "- Which algorithm has the best **feasibility rate**?\n",
        "- How does performance change with **budget** and **start_time**?\n",
    ]),
]

# ── INJECT ─────────────────────────────────────────────────────────────────────

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

cells = nb["cells"]

# Find Section 6 start and Section 7 start
sec6_start = None
sec7_start = None
for i, cell in enumerate(cells):
    src = "".join(cell.get("source", []))
    if "SECTION 6" in src and cell["cell_type"] == "markdown":
        sec6_start = i
    if "SECTION 7" in src and cell["cell_type"] == "markdown":
        sec7_start = i

if sec6_start is None:
    print("ERROR: Could not find SECTION 6 marker")
    exit(1)

end = sec7_start if sec7_start is not None else len(cells)

print(f"Replacing cells [{sec6_start}..{end-1}] with {len(CELLS)} new cells")

nb["cells"] = cells[:sec6_start] + CELLS + cells[end:]

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("Done! Section 6 injected successfully.")
